#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v7
# autospec commit: f56f1fa
#
Name     : R-rhub
Version  : 2.0.0
Release  : 38
URL      : https://cran.r-project.org/src/contrib/rhub_2.0.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/rhub_2.0.0.tar.gz
Summary  : Tools for R Package Developers
Group    : Development/Tools
License  : MIT
Requires: R-R6
Requires: R-callr
Requires: R-cli
Requires: R-curl
Requires: R-desc
Requires: R-gert
Requires: R-gitcreds
Requires: R-glue
Requires: R-jsonlite
Requires: R-pkgbuild
Requires: R-processx
Requires: R-rappdirs
Requires: R-rematch
Requires: R-rprojroot
Requires: R-whoami
BuildRequires : R-R6
BuildRequires : R-callr
BuildRequires : R-cli
BuildRequires : R-curl
BuildRequires : R-desc
BuildRequires : R-gert
BuildRequires : R-gitcreds
BuildRequires : R-glue
BuildRequires : R-jsonlite
BuildRequires : R-pkgbuild
BuildRequires : R-processx
BuildRequires : R-rappdirs
BuildRequires : R-rematch
BuildRequires : R-rprojroot
BuildRequires : R-whoami
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
similar package checks. The 'rhub' package helps you set up
    R-hub v2 for your R package, and start running checks.

%prep
%setup -q -n rhub
pushd ..
cp -a rhub buildavx2
popd
pushd ..
cp -a rhub buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1712851851

%install
export SOURCE_DATE_EPOCH=1712851851
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/rhub/DESCRIPTION
/usr/lib64/R/library/rhub/INDEX
/usr/lib64/R/library/rhub/LICENSE
/usr/lib64/R/library/rhub/Meta/Rd.rds
/usr/lib64/R/library/rhub/Meta/features.rds
/usr/lib64/R/library/rhub/Meta/hsearch.rds
/usr/lib64/R/library/rhub/Meta/links.rds
/usr/lib64/R/library/rhub/Meta/nsInfo.rds
/usr/lib64/R/library/rhub/Meta/package.rds
/usr/lib64/R/library/rhub/NAMESPACE
/usr/lib64/R/library/rhub/NEWS.md
/usr/lib64/R/library/rhub/R/rhub
/usr/lib64/R/library/rhub/R/rhub.rdb
/usr/lib64/R/library/rhub/R/rhub.rdx
/usr/lib64/R/library/rhub/header.md
/usr/lib64/R/library/rhub/help/AnIndex
/usr/lib64/R/library/rhub/help/aliases.rds
/usr/lib64/R/library/rhub/help/figures/logo.png
/usr/lib64/R/library/rhub/help/paths.rds
/usr/lib64/R/library/rhub/help/rhub.rdb
/usr/lib64/R/library/rhub/help/rhub.rdx
/usr/lib64/R/library/rhub/html/00Index.html
/usr/lib64/R/library/rhub/html/R.css
/usr/lib64/R/library/rhub/tests/testthat.R
/usr/lib64/R/library/rhub/tests/testthat/_snaps/api.md
/usr/lib64/R/library/rhub/tests/testthat/_snaps/assertions.md
/usr/lib64/R/library/rhub/tests/testthat/_snaps/check.md
/usr/lib64/R/library/rhub/tests/testthat/_snaps/cli.md
/usr/lib64/R/library/rhub/tests/testthat/_snaps/doctor.md
/usr/lib64/R/library/rhub/tests/testthat/_snaps/gh.md
/usr/lib64/R/library/rhub/tests/testthat/_snaps/platforms.md
/usr/lib64/R/library/rhub/tests/testthat/_snaps/rc.md
/usr/lib64/R/library/rhub/tests/testthat/_snaps/setup.md
/usr/lib64/R/library/rhub/tests/testthat/_snaps/utils.md
/usr/lib64/R/library/rhub/tests/testthat/fixtures/bad.tar.gz
/usr/lib64/R/library/rhub/tests/testthat/fixtures/gh-response-doctor-gql.rds
/usr/lib64/R/library/rhub/tests/testthat/fixtures/gh-response-doctor-rest.rds
/usr/lib64/R/library/rhub/tests/testthat/fixtures/gh-response-gql.rds
/usr/lib64/R/library/rhub/tests/testthat/fixtures/gh-response-post.rds
/usr/lib64/R/library/rhub/tests/testthat/fixtures/gh-response.rds
/usr/lib64/R/library/rhub/tests/testthat/fixtures/manifest.json
/usr/lib64/R/library/rhub/tests/testthat/fixtures/pkg/DESCRIPTION
/usr/lib64/R/library/rhub/tests/testthat/fixtures/pkg/NAMESPACE
/usr/lib64/R/library/rhub/tests/testthat/fixtures/pkg/R/pkg.R
/usr/lib64/R/library/rhub/tests/testthat/fixtures/pkg_0.0.0.9000.tar.gz
/usr/lib64/R/library/rhub/tests/testthat/fixtures/platforms.json
/usr/lib64/R/library/rhub/tests/testthat/fixtures/platforms2.json
/usr/lib64/R/library/rhub/tests/testthat/fixtures/rc-response-list-repos.rds
/usr/lib64/R/library/rhub/tests/testthat/fixtures/rc-response-submit.rds
/usr/lib64/R/library/rhub/tests/testthat/fixtures/rhub.yaml
/usr/lib64/R/library/rhub/tests/testthat/fixtures/validated_emails.csv
/usr/lib64/R/library/rhub/tests/testthat/helpers.R
/usr/lib64/R/library/rhub/tests/testthat/test-api.R
/usr/lib64/R/library/rhub/tests/testthat/test-assertions.R
/usr/lib64/R/library/rhub/tests/testthat/test-check.R
/usr/lib64/R/library/rhub/tests/testthat/test-cli.R
/usr/lib64/R/library/rhub/tests/testthat/test-doctor.R
/usr/lib64/R/library/rhub/tests/testthat/test-gh.R
/usr/lib64/R/library/rhub/tests/testthat/test-http-cache.R
/usr/lib64/R/library/rhub/tests/testthat/test-platforms.R
/usr/lib64/R/library/rhub/tests/testthat/test-rc.R
/usr/lib64/R/library/rhub/tests/testthat/test-rematch.R
/usr/lib64/R/library/rhub/tests/testthat/test-setup.R
/usr/lib64/R/library/rhub/tests/testthat/test-utils.R
